/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.financesystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class account extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(account.class.getName());

    /**
     * Creates new form account
     */
    public account() {
        initComponents();
           loadTable();
    }
    
    
    public void loadTable(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM accounts";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblaccounts.getModel();

        model.setRowCount(0);

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getInt("account_no"),

                rs.getInt("customer_id"),

                rs.getString("account_type"),

                rs.getDouble("balance")

            });

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnreport = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        btncus = new javax.swing.JButton();
        btnacc = new javax.swing.JButton();
        btntransactions = new javax.swing.JButton();
        btnlogout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcusid = new javax.swing.JTextField();
        txtbalance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblaccounts = new javax.swing.JTable();
        btnup = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        comboacc = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        btnreport.setBackground(new java.awt.Color(153, 204, 255));
        btnreport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnreport.setText("Reports");
        btnreport.addActionListener(this::btnreportActionPerformed);

        btndash.setBackground(new java.awt.Color(153, 204, 255));
        btndash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndash.setText("Dashboard");
        btndash.addActionListener(this::btndashActionPerformed);

        btncus.setBackground(new java.awt.Color(153, 204, 255));
        btncus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncus.setText("Customers");
        btncus.addActionListener(this::btncusActionPerformed);

        btnacc.setBackground(new java.awt.Color(153, 204, 255));
        btnacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnacc.setText("Accounts");

        btntransactions.setBackground(new java.awt.Color(153, 204, 255));
        btntransactions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntransactions.setText("Transactions");
        btntransactions.addActionListener(this::btntransactionsActionPerformed);

        btnlogout1.setBackground(new java.awt.Color(153, 204, 255));
        btnlogout1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout1.setText("Logout");
        btnlogout1.addActionListener(this::btnlogout1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnacc, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addComponent(btnreport, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncus, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btndash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btncus)
                .addGap(28, 28, 28)
                .addComponent(btntransactions)
                .addGap(27, 27, 27)
                .addComponent(btnacc)
                .addGap(36, 36, 36)
                .addComponent(btnreport)
                .addGap(35, 35, 35)
                .addComponent(btnlogout1)
                .addGap(382, 382, 382))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Accounts Management");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Customer ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Account Type");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Balance");

        tblaccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account No", "Customer ID", "Account Type", "Balance"
            }
        ));
        tblaccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblaccountsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblaccounts);

        btnup.setBackground(new java.awt.Color(0, 204, 51));
        btnup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnup.setForeground(new java.awt.Color(255, 255, 255));
        btnup.setText("Update");
        btnup.addActionListener(this::btnupActionPerformed);

        btnclear.setBackground(new java.awt.Color(247, 240, 240));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(this::btnclearActionPerformed);

        btncreate.setBackground(javax.swing.UIManager.getDefaults().getColor("nb.startpage.topbar.background"));
        btncreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(255, 255, 255));
        btncreate.setText("Create");
        btncreate.addActionListener(this::btncreateActionPerformed);

        btndel.setBackground(new java.awt.Color(255, 51, 51));
        btndel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndel.setForeground(new java.awt.Color(255, 255, 255));
        btndel.setText("Delete");
        btndel.addActionListener(this::btndelActionPerformed);

        comboacc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Current ", "Fixed" }));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcusid)
                            .addComponent(comboacc, 0, 284, Short.MAX_VALUE)
                            .addComponent(txtbalance)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnup, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboacc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnup, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
try{

    Connection con = DBConnection.getConnection();

    String sql = "INSERT INTO accounts(customer_id,account_type,balance) VALUES(?,?,?)";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, txtcusid.getText());

    pst.setString(2, comboacc.getSelectedItem().toString());

    pst.setString(3, txtbalance.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Account Created");

    loadTable();

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
txtcusid.setText("");

txtbalance.setText("");

comboacc.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
try{

    int row = tblaccounts.getSelectedRow();
    if (row == -1) {
    JOptionPane.showMessageDialog(null, "Please select an account first!");
    return;
}

    String id = tblaccounts.getValueAt(row,0).toString();

    Connection con = DBConnection.getConnection();

    String sql = "UPDATE accounts SET customer_id=?,account_type=?,balance=? WHERE account_no=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, txtcusid.getText());

    pst.setString(2, comboacc.getSelectedItem().toString());

    pst.setString(3, txtbalance.getText());

    pst.setString(4, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Account Updated");

    loadTable();

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnupActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
try{

    int row = tblaccounts.getSelectedRow();
    if (row == -1) {
    JOptionPane.showMessageDialog(null, "Please select an account first!");
    return;
}

    String id = tblaccounts.getValueAt(row,0).toString();

    Connection con = DBConnection.getConnection();

    String sql = "DELETE FROM accounts WHERE account_no=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Account Deleted");

    loadTable();

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btndelActionPerformed

    private void tblaccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblaccountsMouseClicked
int row = tblaccounts.getSelectedRow();
if (row == -1) return;  

txtcusid.setText(tblaccounts.getValueAt(row,1).toString());

comboacc.setSelectedItem(tblaccounts.getValueAt(row,2).toString());

txtbalance.setText(tblaccounts.getValueAt(row,3).toString());    
    }//GEN-LAST:event_tblaccountsMouseClicked

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
new dashboard1().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btndashActionPerformed

    private void btncusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusActionPerformed
new customer().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btncusActionPerformed

    private void btntransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransactionsActionPerformed
new transaction().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btntransactionsActionPerformed

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
new login().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnlogout1ActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
new reports().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new account().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacc;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btncus;
    private javax.swing.JButton btndash;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btntransactions;
    private javax.swing.JButton btnup;
    private javax.swing.JComboBox<String> comboacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblaccounts;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtcusid;
    // End of variables declaration//GEN-END:variables
}
