/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.financesystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author hp
 */
public class customer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(customer.class.getName());

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
        
          loadTable();
    }
    
    
    public void loadTable(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM customers";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

        model.setRowCount(0);

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getInt("customer_id"),

                rs.getString("name"),

                rs.getString("nic"),

                rs.getString("address"),

                rs.getString("phone")

            });

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtpn = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        btns = new javax.swing.JButton();
        btnu = new javax.swing.JButton();
        btnd = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcustomer = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnreport = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        btncus = new javax.swing.JButton();
        btnacc = new javax.swing.JButton();
        btntransactions = new javax.swing.JButton();
        btnlogout1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 0, 482, 74));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 98, 94, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NIC :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 176, 94, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Address :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 222, 94, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Phone  :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 275, 94, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 98, 257, 34));
        getContentPane().add(txtpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 269, 257, 35));
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 216, 257, 35));
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 257, 34));

        btns.setBackground(javax.swing.UIManager.getDefaults().getColor("Table.cellFocusColor"));
        btns.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btns.setForeground(new java.awt.Color(255, 255, 255));
        btns.setText("Save");
        btns.addActionListener(this::btnsActionPerformed);
        getContentPane().add(btns, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 379, 105, 41));

        btnu.setBackground(new java.awt.Color(51, 255, 51));
        btnu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnu.setForeground(new java.awt.Color(255, 255, 255));
        btnu.setText("Update");
        btnu.addActionListener(this::btnuActionPerformed);
        getContentPane().add(btnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 379, 104, 41));

        btnd.setBackground(new java.awt.Color(255, 51, 51));
        btnd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnd.setForeground(new java.awt.Color(255, 255, 255));
        btnd.setText("Delete");
        btnd.addActionListener(this::btndActionPerformed);
        getContentPane().add(btnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 379, 99, 41));

        btnc.setBackground(new java.awt.Color(247, 240, 240));
        btnc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnc.setText("Clear");
        btnc.addActionListener(this::btncActionPerformed);
        getContentPane().add(btnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(963, 379, 99, 41));

        tblcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", " Name ", "NIC", "Address", "Phone"
            }
        ));
        tblcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblcustomer);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 456, -1, 252));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        btnreport.setBackground(new java.awt.Color(153, 204, 255));
        btnreport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnreport.setText("Reports");
        btnreport.addActionListener(this::btnreportActionPerformed);

        btndash.setBackground(new java.awt.Color(153, 204, 255));
        btndash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndash.setText("Dashboard");
        btndash.addActionListener(this::btndashActionPerformed);

        btncus.setBackground(new java.awt.Color(153, 204, 255));
        btncus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncus.setText("Customers");
        btncus.addActionListener(this::btncusActionPerformed);

        btnacc.setBackground(new java.awt.Color(153, 204, 255));
        btnacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnacc.setText("Accounts");
        btnacc.addActionListener(this::btnaccActionPerformed);

        btntransactions.setBackground(new java.awt.Color(153, 204, 255));
        btntransactions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntransactions.setText("Transactions");
        btntransactions.addActionListener(this::btntransactionsActionPerformed);

        btnlogout1.setBackground(new java.awt.Color(153, 204, 255));
        btnlogout1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout1.setText("Logout");
        btnlogout1.addActionListener(this::btnlogout1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnacc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btndash)
                .addGap(39, 39, 39)
                .addComponent(btncus)
                .addGap(37, 37, 37)
                .addComponent(btntransactions)
                .addGap(28, 28, 28)
                .addComponent(btnacc)
                .addGap(35, 35, 35)
                .addComponent(btnreport)
                .addGap(37, 37, 37)
                .addComponent(btnlogout1)
                .addGap(340, 340, 340))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1739, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsActionPerformed
try{

    Connection con = DBConnection.getConnection();

    String sql = "INSERT INTO customers(name,nic,address,phone) VALUES(?,?,?,?)";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, txtname.getText());

    pst.setString(2, txtnic.getText());

    pst.setString(3, txtaddress.getText());

    pst.setString(4, txtpn.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Customer Added");
    loadTable();

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnsActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
txtname.setText("");

txtnic.setText("");

txtaddress.setText("");

txtpn.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btncActionPerformed

    private void btnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuActionPerformed
try{

    int row = tblcustomer.getSelectedRow();
   
if (row == -1) {
    JOptionPane.showMessageDialog(null, "Please select a customer first!");
    return;
}

    String id = tblcustomer.getValueAt(row,0).toString();

    Connection con = DBConnection.getConnection();

    String sql = "UPDATE customers SET name=?,nic=?,address=?,phone=? WHERE customer_id=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, txtname.getText());

    pst.setString(2, txtnic.getText());

    pst.setString(3, txtaddress.getText());

    pst.setString(4, txtpn.getText());

    pst.setString(5, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Customer Updated");

    loadTable();

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnuActionPerformed

    private void btndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndActionPerformed
try{

    int row = tblcustomer.getSelectedRow();
   
if (row == -1) {
    JOptionPane.showMessageDialog(null, "Please select a customer first!");
    return;
}

    String id = tblcustomer.getValueAt(row,0).toString();

    Connection con = DBConnection.getConnection();

    String sql = "DELETE FROM customers WHERE customer_id=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Customer Deleted");

    loadTable();

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btndActionPerformed

    private void tblcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcustomerMouseClicked
                                       
int row = tblcustomer.getSelectedRow();
if (row == -1) return;  // ADD THIS LINE

txtname.setText(tblcustomer.getValueAt(row,1).toString());
txtnic.setText(tblcustomer.getValueAt(row,2).toString());
txtaddress.setText(tblcustomer.getValueAt(row,3).toString());
txtpn.setText(tblcustomer.getValueAt(row,4).toString());       // TODO add your handling code here:
    }//GEN-LAST:event_tblcustomerMouseClicked

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
new dashboard1().setVisible(true);

this.dispose() ;       // TODO add your handling code here:
    }//GEN-LAST:event_btndashActionPerformed

    private void btncusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_btncusActionPerformed

    private void btntransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransactionsActionPerformed
new transaction().setVisible(true);

this.dispose() ;          // TODO add your handling code here:
    }//GEN-LAST:event_btntransactionsActionPerformed

    private void btnaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccActionPerformed
new account().setVisible(true);

this.dispose() ;         // TODO add your handling code here:
    }//GEN-LAST:event_btnaccActionPerformed

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
new login().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnlogout1ActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
new reports().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new customer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacc;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btncus;
    private javax.swing.JButton btnd;
    private javax.swing.JButton btndash;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btns;
    private javax.swing.JButton btntransactions;
    private javax.swing.JButton btnu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblcustomer;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpn;
    // End of variables declaration//GEN-END:variables
}
