/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.financesystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class dashboard1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard1.class.getName());

    /**
     * Creates new form dashboard1
     */
    public dashboard1() {
        initComponents();
        loadCustomers();

    loadAccounts();

    loadTransactions();

    loadBalance();

    loadRecentTransactions();

    }
    
    public void loadCustomers(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT COUNT(*) FROM customers";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        if(rs.next()){

            lblcus.setText(rs.getString(1));

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}
    
    
    public void loadAccounts(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT COUNT(*) FROM accounts";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        if(rs.next()){

            lblta.setText(rs.getString(1));

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}
    
    
    public void loadTransactions(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT COUNT(*) FROM transactions";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        if(rs.next()){

            lbltt.setText(rs.getString(1));

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}
    
    
    
    public void loadBalance(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT SUM(balance) FROM accounts";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        if(rs.next()){

            lbltb.setText(rs.getString(1));

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}
    
    
    public void loadRecentTransactions(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM transactions ORDER BY transaction_id DESC LIMIT 5";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblrecent.getModel();

        model.setRowCount(0);

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getInt("transaction_id"),

                rs.getInt("account_no"),

                rs.getString("transaction_type"),

                rs.getDouble("amount")

            });

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnreport = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        btncus = new javax.swing.JButton();
        btnacc = new javax.swing.JButton();
        btntransactions = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblc = new javax.swing.JPanel();
        lblcus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblta = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbltt = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbltb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrecent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        btnreport.setBackground(new java.awt.Color(153, 204, 255));
        btnreport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnreport.setText("Reports");
        btnreport.addActionListener(this::btnreportActionPerformed);

        btnlogout.setBackground(new java.awt.Color(153, 204, 255));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(this::btnlogoutActionPerformed);

        btndash.setBackground(new java.awt.Color(153, 204, 255));
        btndash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndash.setText("Dashboard");

        btncus.setBackground(new java.awt.Color(153, 204, 255));
        btncus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncus.setText("Customers");
        btncus.addActionListener(this::btncusActionPerformed);

        btnacc.setBackground(new java.awt.Color(153, 204, 255));
        btnacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnacc.setText("Accounts");
        btnacc.addActionListener(this::btnaccActionPerformed);

        btntransactions.setBackground(new java.awt.Color(153, 204, 255));
        btntransactions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntransactions.setText("Transactions");
        btntransactions.addActionListener(this::btntransactionsActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btndash)
                .addGap(43, 43, 43)
                .addComponent(btncus)
                .addGap(48, 48, 48)
                .addComponent(btnacc)
                .addGap(55, 55, 55)
                .addComponent(btntransactions)
                .addGap(52, 52, 52)
                .addComponent(btnreport)
                .addGap(46, 46, 46)
                .addComponent(btnlogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.SystemColor.inactiveCaption);

        lblc.setBackground(java.awt.SystemColor.activeCaption);

        lblcus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcus.setText(" Total Customers");

        javax.swing.GroupLayout lblcLayout = new javax.swing.GroupLayout(lblc);
        lblc.setLayout(lblcLayout);
        lblcLayout.setHorizontalGroup(
            lblcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblcLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblcus)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        lblcLayout.setVerticalGroup(
            lblcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblcLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblcus)
                .addGap(41, 41, 41))
        );

        jPanel5.setBackground(java.awt.SystemColor.activeCaption);

        lblta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblta.setText("Total Accounts");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblta)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel6.setBackground(java.awt.SystemColor.activeCaption);

        lbltt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltt.setText("Total Transactions");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbltt)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel7.setBackground(java.awt.SystemColor.activeCaption);

        lbltb.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        lbltb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltb.setText("Total Balance");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lbltb, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbltb)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        tblrecent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Account No", "Type", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblrecent);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Trust Bank Dashboard");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking/financesystem/download (4).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusActionPerformed
new customer().setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncusActionPerformed

    private void btnaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccActionPerformed
new account().setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnaccActionPerformed

    private void btntransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransactionsActionPerformed
new transaction().setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btntransactionsActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
new reports().setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
new login().setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacc;
    private javax.swing.JButton btncus;
    private javax.swing.JButton btndash;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btntransactions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lblc;
    private javax.swing.JLabel lblcus;
    private javax.swing.JLabel lblta;
    private javax.swing.JLabel lbltb;
    private javax.swing.JLabel lbltt;
    private javax.swing.JTable tblrecent;
    // End of variables declaration//GEN-END:variables
}
