/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.financesystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hp
 */
public class reports extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(reports.class.getName());

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnreport = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        btncus = new javax.swing.JButton();
        btnacc = new javax.swing.JButton();
        btntransactions = new javax.swing.JButton();
        btnlogout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btncustomers = new javax.swing.JButton();
        btnaccount = new javax.swing.JButton();
        btntransa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreports = new javax.swing.JTable();
        lbltotal = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btncustomerrep = new javax.swing.JButton();
        btnaccountrep = new javax.swing.JButton();
        btntransactionrep = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        btnreport.setBackground(new java.awt.Color(153, 204, 255));
        btnreport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnreport.setText("Reports");

        btndash.setBackground(new java.awt.Color(153, 204, 255));
        btndash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndash.setText("Dashboard");
        btndash.addActionListener(this::btndashActionPerformed);

        btncus.setBackground(new java.awt.Color(153, 204, 255));
        btncus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncus.setText("Customers");
        btncus.addActionListener(this::btncusActionPerformed);

        btnacc.setBackground(new java.awt.Color(153, 204, 255));
        btnacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnacc.setText("Accounts");
        btnacc.addActionListener(this::btnaccActionPerformed);

        btntransactions.setBackground(new java.awt.Color(153, 204, 255));
        btntransactions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntransactions.setText("Transactions");
        btntransactions.addActionListener(this::btntransactionsActionPerformed);

        btnlogout1.setBackground(new java.awt.Color(153, 204, 255));
        btnlogout1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout1.setText("Logout");
        btnlogout1.addActionListener(this::btnlogout1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnacc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btncus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addComponent(btnlogout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btndash)
                .addGap(33, 33, 33)
                .addComponent(btncus)
                .addGap(35, 35, 35)
                .addComponent(btntransactions)
                .addGap(36, 36, 36)
                .addComponent(btnacc)
                .addGap(46, 46, 46)
                .addComponent(btnreport)
                .addGap(41, 41, 41)
                .addComponent(btnlogout1)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report Management");

        btncustomers.setText("Load Customers");
        btncustomers.addActionListener(this::btncustomersActionPerformed);

        btnaccount.setText("Load Accounts");
        btnaccount.addActionListener(this::btnaccountActionPerformed);

        btntransa.setText("Load Transactions");
        btntransa.addActionListener(this::btntransaActionPerformed);

        tblreports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Account No", "Type", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblreports);

        lbltotal.setText("Total Records :");

        btncustomerrep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncustomerrep.setText("Customer Report");
        btncustomerrep.addActionListener(this::btncustomerrepActionPerformed);

        btnaccountrep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnaccountrep.setText("Account Report");
        btnaccountrep.addActionListener(this::btnaccountrepActionPerformed);

        btntransactionrep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntransactionrep.setText("Transaction Report");
        btntransactionrep.addActionListener(this::btntransactionrepActionPerformed);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btncustomers)
                        .addGap(134, 134, 134)
                        .addComponent(btnaccount)
                        .addGap(139, 139, 139)
                        .addComponent(btntransa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncustomerrep, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btnaccountrep, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btntransactionrep, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(217, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntransactionrep)
                    .addComponent(btnaccountrep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncustomerrep))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntransa)
                    .addComponent(btncustomers)
                    .addComponent(btnaccount))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltotal)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomersActionPerformed
try{

    Connection con = DBConnection.getConnection();

    String sql = "SELECT * FROM customers";

    PreparedStatement pst = con.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Name");
    model.addColumn("NIC");
    model.addColumn("Address");
    model.addColumn("Phone");

    int count = 0;

    while(rs.next()){

        model.addRow(new Object[]{

            rs.getInt("customer_id"),

            rs.getString("name"),

            rs.getString("nic"),

            rs.getString("address"),

            rs.getString("phone")

        });

        count++;

    }

    tblreports.setModel(model);

    lbltotal.setText(String.valueOf(count));

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btncustomersActionPerformed

    private void btnaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccountActionPerformed
try{

    Connection con = DBConnection.getConnection();

    String sql = "SELECT * FROM accounts";

    PreparedStatement pst = con.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("Account No");
    model.addColumn("Customer ID");
    model.addColumn("Account Type");
    model.addColumn("Balance");

    int count = 0;

    while(rs.next()){

        model.addRow(new Object[]{

            rs.getInt("account_no"),

            rs.getInt("customer_id"),

            rs.getString("account_type"),

            rs.getDouble("balance")

        });

        count++;

    }

    tblreports.setModel(model);

    lbltotal.setText(String.valueOf(count));

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnaccountActionPerformed

    private void btntransaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaActionPerformed
try{

    Connection con = DBConnection.getConnection();

    String sql = "SELECT * FROM transactions";

    PreparedStatement pst = con.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("Transaction ID");
    model.addColumn("Account No");
    model.addColumn("Type");
    model.addColumn("Amount");

    int count = 0;

    while(rs.next()){

        model.addRow(new Object[]{

            rs.getInt("transaction_id"),

            rs.getInt("account_no"),

            rs.getString("transaction_type"),

            rs.getDouble("amount")

        });

        count++;

    }

    tblreports.setModel(model);

    lbltotal.setText(String.valueOf(count));

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btntransaActionPerformed

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
new dashboard1().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btndashActionPerformed

    private void btncusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusActionPerformed
new customer().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btncusActionPerformed

    private void btntransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransactionsActionPerformed
new transaction().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btntransactionsActionPerformed

    private void btnaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccActionPerformed
new account().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnaccActionPerformed

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
new login().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnlogout1ActionPerformed

    private void btncustomerrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerrepActionPerformed
try {
    Connection con = DBConnection.getConnection();

    JasperPrint jp = JasperFillManager.fillReport(
        getClass().getResourceAsStream("/report/customer_reportt.jasper"),
        new HashMap(),
        con
    );

    JasperViewer.viewReport(jp, false);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_btncustomerrepActionPerformed

    private void btnaccountrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccountrepActionPerformed
try {
    Connection con = DBConnection.getConnection();

    JasperPrint jp = JasperFillManager.fillReport(
        getClass().getResourceAsStream("/report/account_report.jasper"),
        new HashMap(),
        con
    );

    JasperViewer.viewReport(jp, false);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_btnaccountrepActionPerformed

    private void btntransactionrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransactionrepActionPerformed
try {
    Connection con = DBConnection.getConnection();

    JasperPrint jp = JasperFillManager.fillReport(
        getClass().getResourceAsStream("/report/transaction_reportt.jasper"),
        new HashMap(),
        con
    );

    JasperViewer.viewReport(jp, false);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_btntransactionrepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new reports().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacc;
    private javax.swing.JButton btnaccount;
    private javax.swing.JButton btnaccountrep;
    private javax.swing.JButton btncus;
    private javax.swing.JButton btncustomerrep;
    private javax.swing.JButton btncustomers;
    private javax.swing.JButton btndash;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btntransa;
    private javax.swing.JButton btntransactionrep;
    private javax.swing.JButton btntransactions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tblreports;
    // End of variables declaration//GEN-END:variables
}
