/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.financesystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class transaction extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(transaction.class.getName());

    /**
     * Creates new form transaction
     */
    public transaction() {
        initComponents();
        loadTable();
    }
    
    
    public void loadTable(){

    try{

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM transactions";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tbltransactions.getModel();

        model.setRowCount(0);

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getInt("transaction_id"),

                rs.getInt("account_no"),

                rs.getString("transaction_type"),

                rs.getDouble("amount")

            });

        }

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(null, e);

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnreport = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        btncus = new javax.swing.JButton();
        btnacc = new javax.swing.JButton();
        btntransactions = new javax.swing.JButton();
        btnlogout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtaccno = new javax.swing.JTextField();
        cmbtt = new javax.swing.JComboBox<>();
        txtam = new javax.swing.JTextField();
        btnprocess = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltransactions = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        btnreport.setBackground(new java.awt.Color(153, 204, 255));
        btnreport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnreport.setText("Reports");
        btnreport.addActionListener(this::btnreportActionPerformed);

        btndash.setBackground(new java.awt.Color(153, 204, 255));
        btndash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndash.setText("Dashboard");
        btndash.addActionListener(this::btndashActionPerformed);

        btncus.setBackground(new java.awt.Color(153, 204, 255));
        btncus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncus.setText("Customers");
        btncus.addActionListener(this::btncusActionPerformed);

        btnacc.setBackground(new java.awt.Color(153, 204, 255));
        btnacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnacc.setText("Accounts");
        btnacc.addActionListener(this::btnaccActionPerformed);

        btntransactions.setBackground(new java.awt.Color(153, 204, 255));
        btntransactions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntransactions.setText("Transactions");

        btnlogout1.setBackground(new java.awt.Color(153, 204, 255));
        btnlogout1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout1.setText("Logout");
        btnlogout1.addActionListener(this::btnlogout1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnacc, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btncus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addComponent(btnlogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreport, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btndash)
                .addGap(51, 51, 51)
                .addComponent(btncus)
                .addGap(52, 52, 52)
                .addComponent(btntransactions)
                .addGap(51, 51, 51)
                .addComponent(btnacc)
                .addGap(45, 45, 45)
                .addComponent(btnreport)
                .addGap(49, 49, 49)
                .addComponent(btnlogout1)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Transaction Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 16, 473, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Account Number :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Transaction Type :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 168, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Amount :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 75, -1));
        getContentPane().add(txtaccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 290, 37));

        cmbtt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdraw" }));
        getContentPane().add(cmbtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 290, 36));
        getContentPane().add(txtam, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 290, 40));

        btnprocess.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.icon.checkmarkColor"));
        btnprocess.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnprocess.setForeground(new java.awt.Color(255, 255, 255));
        btnprocess.setText("Process");
        btnprocess.addActionListener(this::btnprocessActionPerformed);
        getContentPane().add(btnprocess, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 114, 38));

        btnclear.setBackground(new java.awt.Color(247, 240, 240));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(this::btnclearActionPerformed);
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 127, 38));

        tbltransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Account No", "Type", "Amount"
            }
        ));
        tbltransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltransactionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltransactions);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 482, -1, 288));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1283, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 836, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocessActionPerformed
try{

    Connection con = DBConnection.getConnection();

    long accNo = Long.parseLong(txtaccno.getText());

    double amount = Double.parseDouble(txtam.getText());

    String type = cmbtt.getSelectedItem().toString();

    double currentBalance = 0;

    String getBalance = "SELECT balance FROM accounts WHERE account_no=?";

    PreparedStatement pst1 = con.prepareStatement(getBalance);

    pst1.setLong(1, accNo);

    ResultSet rs = pst1.executeQuery();

    if(rs.next()){

        currentBalance = rs.getDouble("balance");

    }

    double newBalance = 0;

    if(type.equals("Deposit")){

        newBalance = currentBalance + amount;

    }
    else{

        if(amount > currentBalance){

            JOptionPane.showMessageDialog(null, "Insufficient Balance");

            return;

        }

        newBalance = currentBalance - amount;

    }

    String updateBalance = "UPDATE accounts SET balance=? WHERE account_no=?";

    PreparedStatement pst2 = con.prepareStatement(updateBalance);

    pst2.setDouble(1, newBalance);

    pst2.setLong(2, accNo);

    pst2.executeUpdate();

    String saveTransaction = "INSERT INTO transactions(account_no,transaction_type,amount) VALUES(?,?,?)";

    PreparedStatement pst3 = con.prepareStatement(saveTransaction);

    pst3.setLong(1, accNo);

    pst3.setString(2, type);

    pst3.setDouble(3, amount);

    pst3.executeUpdate();

    JOptionPane.showMessageDialog(null, "Transaction Successful");

    loadTable();

}
catch(Exception e){

    JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnprocessActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
txtaccno.setText("");

txtam.setText("");

cmbtt.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void tbltransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltransactionsMouseClicked
int row = tbltransactions.getSelectedRow();


txtaccno.setText(tbltransactions.getValueAt(row,1).toString());

cmbtt.setSelectedItem(tbltransactions.getValueAt(row,2).toString());

txtam.setText(tbltransactions.getValueAt(row,3).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tbltransactionsMouseClicked

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
new dashboard1().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btndashActionPerformed

    private void btncusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusActionPerformed
new customer().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btncusActionPerformed

    private void btnaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccActionPerformed
new account().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnaccActionPerformed

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
new login().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnlogout1ActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
new reports().setVisible(true);

this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new transaction().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacc;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncus;
    private javax.swing.JButton btndash;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton btnprocess;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btntransactions;
    private javax.swing.JComboBox<String> cmbtt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltransactions;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtam;
    // End of variables declaration//GEN-END:variables
}
